# Generated by Django 5.0 on 2024-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='', upload_to='books_image'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='', upload_to='books_pdfs'),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=3),
        ),
    ]
