# Generated by Django 5.0 on 2024-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0002_book_book_cover_book_book_file_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='', upload_to='bookmanagement/books_image'),
        ),
    ]
