# Generated by Django 5.0.3 on 2024-03-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0003_alter_book_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
    ]
