# Generated by Django 5.0 on 2024-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_borrowed',
            field=models.PositiveIntegerField(default='', null=True),
        ),
    ]
