# Generated by Django 5.0 on 2024-03-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
