# Generated by Django 5.0.3 on 2024-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_books_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_borrowed',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
