# Generated by Django 5.0.2 on 2024-03-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_books_borrowed_alter_user_is_banned'),
        ('account', '0003_delete_book'),
    ]

    operations = [
    ]
